name: VK to Telegram Bot

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests
    
    - name: Download cache
      uses: actions/download-artifact@v4
      with:
        name: vk-bot-cache
        path: ./
      continue-on-error: true
    
    - run: |
        if [ ! -f last_ids.json ]; then
          echo "{}" > last_ids.json
        fi
    
    - name: Run bot
      env:
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: python bot.py
    
    - name: Upload cache
      uses: actions/upload-artifact@v3
      with:
        name: vk-bot-cache
        path: last_ids.json
        retention-days: 7
